// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB14_rp_F7P8xnwgH6RTcrWVaUIuPjSsU',
    appId: '1:665086885932:android:c8a10f42861d1e9c499189',
    messagingSenderId: '665086885932',
    projectId: 'calorii-fit-app',
    storageBucket: 'calorii-fit-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRORfmLRcBPQFlW6DX5hOeRDduxBAdXiA',
    appId: '1:665086885932:ios:d6ac1abeeb52f337499189',
    messagingSenderId: '665086885932',
    projectId: 'calorii-fit-app',
    storageBucket: 'calorii-fit-app.firebasestorage.app',
    androidClientId: '665086885932-unrqnv8scjlgame498ok95kpqr41mr41.apps.googleusercontent.com',
    iosClientId: '665086885932-r6qsq0vko2c4ki3uga8tv2l4tp70p551.apps.googleusercontent.com',
    iosBundleId: 'com.kappa.calorieapp.calorieApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJhNpuCwB-VB413qSGP0qDQl0SCiUhik',
    appId: '1:665086885932:web:5ffdbf59f89046e2499189',
    messagingSenderId: '665086885932',
    projectId: 'calorii-fit-app',
    authDomain: 'calorii-fit-app.firebaseapp.com',
    storageBucket: 'calorii-fit-app.firebasestorage.app',
  );
}
